### ISSUE TITLE
Multiple views need to be updated post-route

### ISSUE THREAD

**Issue by jmeas** [jmeas/backbone.state-router#14]
A page of widgets. The URI changes. Each widget need to know. 

//cc @megawac

p.s. self, also think of those widgets I made at OneTwoSee.

**Comment by jmeas** [comment]
This solution will be more closely considered in a different routing lib.

**Comment by megawac** [comment]
Didn't have any luck with this one?

**Comment by jmeas** [comment]
I didn't spend much time looking into it, tbh. I'm working on a **far** better routing library than what you can build on top of the BaseRouter, though.
